[JBBotSquadArena]
TextArena="combat dans l'arène"

[JBBotSquadJail]
TextJailed="en prison"

[JBGUIPageClientOptions]
DialogTitle.Caption="Jailbreak Client Options"
CancelButton.Caption="Annuler"
CancelButton.Hint="Cliquez pour fermer ce menu en rejetant les modifications."
EnableScreens.Caption="Activer les Textures des Ecrans Dynamiques"
EnableScreens.Hint="Au cas où vous voudriez voir les écrans dynamiques placés dans quelques-unes des maps Jailbreak. Désactiver cette option pourrait améliorer votre framerate."
OkButton.Caption="OK"
OkButton.Hint="Cliquez pour fermer ce menu en sauvegardant les modifications."
ResetButton.Caption="Par défaut"
ResetButton.Hint="Restaurer les valeurs par défaut."
VoicePack.Caption="Annonceur"
VoicePack.Hint="L'annonceur à utiliser dans Jailbreak."
TestVoicePackButton.Caption="Test"
TestVoicePackButton.Hint="Cliquez pour jouer un son au hazard du voice pack selectionné"

[JBGUIHook]
TextCaptionGoalScore="Limite de Captures"
TextCaptionAddons="Add-Ons"
TextHintAddons="Sélectionnez et configurez les add-ons Jailbreak que vous souhaitez utiliser..."

[JBGUITabPanelAddons]
TextHintReset="Réinitialiser les options pour %addon%."
GUIButtonConfigResetDef.Caption="Réinitialiser Options"
GUIButtonConfigResetDef.Hint="Réinitialiser les options de cet add-on."
GUIButtonDownloadAddonsDef.Caption="Télécharger d'autres Add-Ons!"
GUIButtonDownloadAddonsDef.Hint="Lance la page web de téléchargement des add-ons de PlanetJailbreak."
GUILabelConfigDefaultDef.Caption="Cet add-on n'a pas d'option configurable."

[JBInteractionKeys]
TextDialogTitle="Raccoucis Clavier Temporaires"
TextDialogTopS="Jailbreak a assigné temporairement cette touche pour vous:"
TextDialogTopP="Jailbreak a assigné temporairement ces touches pour vous:"
TextDialogBottomS="Configurez les raccourcis pour assigner définitivement une touche à cette fonction."
TextDialogBottomP="Configurez les raccourcis pour assigner définitivement des touches à ces fonctions."
TextDialogClose="Tapez TIR pour fermer, TIR-SECONDAIRE pour supprimer"
TextDescription=("Fixe les tactiques d'équipe sur un mode plus agressif.","Fixe les tactiques d'équipe sur un mode plus défensif.","Revient sur la sélection auto des tactiques d'équipe.","Active la Vue depuis l'Arène.")

[JBInteractionPanorama]
TextInstructionsHidden="Appuyez sur MAJ+H pour afficher les instructions."
TextInstructions[0]="MODE DE REGLAGE DE LA CARTE PANORAMA DU TABLEAU DE SCORES"
TextInstructions[3]="ETAPE 1: Déplacez la caméra vers une position d'où vous avez une bonne vue de toute la map."
TextInstructions[4]="         Appuyez sur MAJ+PLUS NUM et sur MAJ+MOINS NUM pour zoomer et dézoomer, MAJ+ETOILE NUM pour remettre à zéro."
TextInstructions[6]="ETAPE 2: Appuyez sur MAJ+S pour faire une capture d'écran de la map."
TextInstructions[7]="         Appuyez sur MAJ+C pour copier un acteur JBPanorama préétabli sur le clipboard."
TextInstructions[9]="ETAPE 3: Utilisez la capture d'écran pour créer une texture montrant un panorama de votre map."
TextInstructions[10]="         Importez-la dans le package MyLevel de votre map."
TextInstructions[11]="         Rechargez Jailbreak.u et collez l'acteur JBPanorama depuis le clipboard à votre map."
TextInstructions[12]="         Définissez les propriétés TexturePanorama de la texture panorama importée."
TextInstructions[15]="Appuyez sur MAJ+H pour masquer ces instructions."
TextInstructions[16]="Appuyez sur MAJ+X pour quitter le mode de réglage."
TextStatusCopy="Acteur JBPanorama copié sur le clipboard."
TextStatusScreenshot="Capture d'écran enregistrée sous le nom de la dernière image Shot?????.bmp dans votre dossier ScreenShots."

[JBInterfaceHud]
TextPlayerKilled="Vous avez été tué."
TextPlayerExecuted="Vous avez été exécuté."
TextMenuEntryTactics="Tactiques d'équipe"
TextMenuTitleTactics="Tactiques d'équipe"
TextOrderName[0]="[AUTO]"
TextOrderName[1]="Suicidaire"
TextOrderName[2]="Agressif"
TextOrderName[3]="Normal"
TextOrderName[4]="Défensif"
TextOrderName[5]="Evasif"
TextTactics[0]="évasif"
TextTactics[1]="défensif"
TextTactics[2]="normal"
TextTactics[3]="agressif"
TextTactics[4]="suicidaire"
TextArenaNotifier="combat dans l'arène"

[JBInterfaceScores]
TextGameBotmatch="Botmatch"
TextGameOnline="Match Online dans"
TextSkill[0]="Novice"
TextSkill[1]="Moyen"
TextSkill[2]="Expérimenté"
TextSkill[3]="Habile"
TextSkill[4]="Initié"
TextSkill[5]="Maître"
TextSkill[6]="Expert"
TextSkill[7]="Professionnel"
TextLimitPrefix=" ["
TextLimitTime="minutes"
TextLimitScore="captures"
TextLimitSuffix=" max]"
TextInfoWaiting="spectateur"
TextInfoDead="mort"
TextInfoArena="arène"
TextInfoJail="en prison"
TextOrdersUndisclosed="inconnu"
TextOrdersAttack="attaque"
TextOrdersDefense="défense"
TextOrdersFreelance="balayeur"
TextScoresAttack="attaque(s)"
TextScoresDefense="défense(s)"
TextScoresRelease="libération(s)"
TextRelationElapsed="jouées"
TextRelationRemaining="à jouer"
TextRelationOvertime="prolongation"

[JBLocalMessage]
TextTeamCaptured[0]="L'équipe rouge s'est fait capturer."
TextTeamCaptured[1]="L'équipe bleue s'est fait capturer."
TextTeamReleased[0]="L'équipe rouge est libérée."
TextTeamReleased[1]="L'équipe bleue est libérée."
TextTeamReleasedBy[0]="L'équipe rouge est libérée par %player%."
TextTeamReleasedBy[1]="L'équipe bleue est libérée par %player%."
TextTeamReleasedNobody="Cette prison est vide."
TextTeamStalemate="Les deux équipes ont été capturées. Aucune ne marque."
TextArenaCountdown[0]="Un combat dans l'arène va commencer...1"
TextArenaCountdown[1]="Un combat dans l'arène va commencer...2"
TextArenaCountdown[2]="Un combat dans l'arène va commencer...3"
TextArenaStartCombatant="Le combat dans l'arène a commencé!"
TextArenaStartOther="%teammate% affronte %enemy% dans l'arène."
TextArenaCancelCombatant="Le combat dans l'arène entre %teammate% et %enemy% est annulé."
TextArenaCancelOther="Le combat dans l'arène est annulé."
TextArenaTieCombatant="Combat dans l'arène : égalité."
TextArenaTieOther="Le combat dans l'arène entre %teammate% et %enemy% s'est terminé sur une égalité."
TextArenaEndWinner="Vous avez gagné votre liberté!"
TextArenaEndLoser="Vous avez perdu le duel."
TextArenaEndOther="%winner% a battu %loser% dans l'arène."
TextKeyboardArenaBound="Appuyez sur [%key%] pour assister au combat dans l'arène!"
TextKeyboardArenaUnbound="Tapez 'ArenaCam' dans la console pour assister au combat dans l'arène!"
TextKeyboardCameraBound="Appuyez sur [%keyprev%] et [%keynext%] pour passer d'une caméra à l'autre"
TextKeyboardCameraUnbound="Tapez 'PrevWeapon' et 'NextWeapon' dans la console pour passer d'une caméra à l'autre"
TextLastMan="Vous êtes le dernier. Libérez votre équipe!"

[JBMutatorDebug]
FriendlyName="Jailbreak Debug"
Description="Fournit des fonctions d'aide pour la mise au point de maps et de code pour Jailbreak."

[JBPanorama]
TextSetup="Tapez SetupPanorama dans la console"
TextPreview="prévisualisation uniquement, assignez une TexturePanorama"

[Jailbreak]
TextWebAdminEnableJailFights="Activer Combats en Prison"
TextWebAdminFavorHumansForArena="L'arène preferre les humains"
TextWebAdminPrefixAddon="Jailbreak:"
GameName="Jailbreak"
Description="Deux équipes s'affrontent pour fragger les joueurs adverses et ainsi les envoyer dans une prison. Lorsque tous les membres d'une équipe sont emprisonnés, l'équipe adverse marque un point. Frayez-vous un passage à travers la base ennemie pour libérer vos équipiers!"

[JBGUITabPanelRules]
moCheckBoxJailFightsDef.Caption="Activer Combats en Prison"
moCheckBoxJailFightsDef.Hint="Permet aux coéquipiers emprisonnés de se battre entre eux avec leur Marteau Bouclier par pur plaisir."
moCheckBoxFavorHumansForArenaDef.Caption="L'arène preferre les humains"
moCheckBoxFavorHumansForArenaDef.Hint="Les humains sont preferrés aux robots pour les combats d'arène."
GUIButtonConfigureAddonsDef.Caption="Configurer les Add-ons Jailbreak"
GUIButtonConfigureAddonsDef.Hint="Ouvrir le tab des Add-Ons pour les choisir et configurer."

[JBGUIButtonClientOptions]
Caption="OPTIONS JAILBREAK"
